### ISSUE TITLE
Error when trying to use this plugin

### ISSUE THREAD

**Issue by RyanSMurphy** [EddyVerbruggen/nativescript-gradient#3]
Hi, when trying to use this plugin I get the following error. Do you have any advice on how this can be resolved?

```
CONSOLE ERROR file:///app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:344:22: Error: Uncaught (in promise): Error: Error in pages/login/login.html:1:3 caused by: Could not load view for: Gradient.TypeError: undefined is not a constructor (evaluating 'new view_1.Property({
	    name: "direction",
	    defaultValue: "to bottom
```

**Comment by EddyVerbruggen** [comment]
Sure, but I'll need your code. Can you share it?

**Comment by RyanSMurphy** [comment]
Hi this was happening when using nativescript 2, after the upgrade to 3 it didnt happen.

**Comment by EddyVerbruggen** [comment]
I had a hunch that was the issue but figured [this](https://github.com/EddyVerbruggen/nativescript-gradient/blob/master/src/package.json#L9-L10) would guard against that.

Thanks for letting me know!

**Comment by EddyVerbruggen** [comment]
Oh, in case you've created something cool with this plugin don't hesitate to throw a screenshot in this issue, I'd love to see how it's being used in the wild 👍
